/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication8;

/**
 *
 * @author Utente
 */
public class panello extends javax.swing.JPanel {

    /**
     * Creates new form panello
     */
    public panello() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(null);

        jButton1.setText("Colpisci");
        add(jButton1);
        jButton1.setBounds(590, 300, 120, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\bucoTalpa.jpg")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(510, 160, 260, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\bucoTalpa.jpg")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 260, 140);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\bucoTalpa.jpg")); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(510, 0, 260, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\bucoTalpa.jpg")); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 160, 260, 140);

        jButton2.setText("Colpisci");
        add(jButton2);
        jButton2.setBounds(80, 140, 120, 23);

        jButton3.setText("Colpisci");
        add(jButton3);
        jButton3.setBounds(580, 140, 130, 23);

        jButton4.setText("Colpisci");
        add(jButton4);
        jButton4.setBounds(70, 300, 130, 23);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
