/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication8;

/**
 *
 * @author Utente
 */
public class panello extends javax.swing.JPanel {

    /**
     * Creates new form panello
     */
    public panello() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setLayout(null);

        jButton1.setText("Colpisci");
        add(jButton1);
        jButton1.setBounds(580, 190, 120, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\bucoTalpa.jpg")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(490, 50, 260, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\bucoTalpa.jpg")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(40, 80, 260, 140);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\bucoTalpa.jpg")); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(990, 80, 260, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\bucoTalpa.jpg")); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(980, 510, 260, 140);

        jButton2.setText("Colpisci");
        add(jButton2);
        jButton2.setBounds(120, 220, 120, 23);

        jButton3.setText("Colpisci");
        add(jButton3);
        jButton3.setBounds(1080, 220, 130, 23);

        jButton4.setText("Colpisci");
        add(jButton4);
        jButton4.setBounds(1060, 650, 130, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\bucoTalpa.jpg")); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(490, 370, 260, 140);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Utente\\Desktop\\bucoTalpa.jpg")); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 320, 260, 140);

        jButton5.setText("Colpisci");
        add(jButton5);
        jButton5.setBounds(560, 510, 130, 30);

        jButton6.setText("Colpisci");
        add(jButton6);
        jButton6.setBounds(70, 460, 130, 23);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jPanel1);
        jPanel1.setBounds(1380, 0, 160, 220);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
